language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10"
  - "12"
before_script:
  - npm prune
install:
  - npm install
script:
  - npm run build
  - npm run test
after_success:
  - npm run ci:github-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
