language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
install:
  - npm install
script:
  - npm run lint:all
  - npm run build
  - npm run test
after_success:
  - npm run ci:github-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
